project:
  type: website
  output-dir: _site

website:
  title: "Watanabe's Singular Learning Theory"
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/gustavdelius/Watanabe
    left:
      - href: index.qmd
        text: Home
      - href: cheat_sheet.qmd
        text: Cheat Sheet
      - href: regular_and_singular_models.qmd
        text: Regular and Singular Models
      - href: slt_gaussian_mixture.qmd
        text: SLT Gaussian Mixture
      - href: neural_network_figure_2_7.qmd
        text: Neural Network (Figure 2.7)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  cache: true
