project:
  type: website
  output-dir: _site

website:
  title: "Watanabe's Singular Learning Theory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slt_gaussian_mixture.qmd
        text: SLT Gaussian Mixture
      - href: regular_and_singular_models.qmd
        text: Regular and Singular Models
      - href: cheat_sheet.qmd
        text: Cheat Sheet

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
